
CREATE TABLE TITHER
(
	ID_TITHER	  				UNIQUEIDENTIFIER    	    NOT NULL,
    NAME_TITHER  				VARCHAR(100)				NULL,
    ADDRESS_TITHER				VARCHAR(200)				NULL,
    NUMBER_TITHER				INT							NULL,
    NEIGHBORHOOD				VARCHAR(100)				NULL,
    E_MAIL						VARCHAR(100)				NULL,
    CELLPHONE					VARCHAR(20)					NULL,
    TELEPHONE					VARCHAR(20)					NULL,
    BIRTH_DATE					DATE					NOT	NULL,
    MARRIAGE_DATE				DATE						NULL,
	NAME_SPOUSE					VARCHAR(100)				NULL,
    NAME_SON					VARCHAR(100)				NULL,
	BIRTH_DATE_SON				DATE						NULL,
    ACTIVE SMALLINT NOT NULL,
    CPF_TITHER VARCHAR(20) NOT NULL,
    DATE_BIRTH_SPOUSE DATE NULL,
    MATIRAL_STATUS SMALLINT NULL,
    REGISTER_DATE DATETIME NOT NULL,
    
    PRIMARY KEY CLUSTERED (ID_TITHER)
    WITH (
      PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF,
      ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)

);


CREATE TABLE TITHE
(
	ID_TITHE	  				UNIQUEIDENTIFIER    	    NOT NULL,
    VALUE_CONTRIBUTION  				DECIMAL				NULL,
    DATE_CONTRIBUTION				DATE				NULL,
    TITHER_ID				UNIQUEIDENTIFIER							NULL,
	REGISTER_DATE DATETIME NOT NULL,
    
    
    PRIMARY KEY CLUSTERED (ID_TITHE)
    WITH (
      PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF,
      ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)

);
