
CREATE TABLE TITHER
(
	ID_TITHER	  				VARCHAR(36) 			    NOT NULL,
    NAME_TITHER  				VARCHAR(100)				NULL,
    ADDRESS_TITHER				VARCHAR(200)				NULL,
    NUMBER_TITHER				INT							NULL,
    NEIGHBORHOOD				VARCHAR(100)				NULL,
    E_MAIL						VARCHAR(100)				NULL,
    CELLPHONE					VARCHAR(20)					NULL,
    TELEPHONE					VARCHAR(20)					NULL,
    BIRTH_DATE					DATE					NOT	NULL,
    MARRIAGE_DATE				DATE						NULL,
	NAME_SPOUSE					VARCHAR(100)				NULL,
    BIRTH_DATE_SPOUSE			DATE						NULL,
    NAME_SON					VARCHAR(100)				NULL,
	BIRTH_DATE_SON				DATE						NULL,
    
    PRIMARY KEY CLUSTERED (ID_TITHER)
    WITH (
      PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF,
      ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)

);

alter table tither add ACTIVE SMALLINT;
alter table tither add CPF_TITHER VARCHAR(20);
alter table tither add DATE_BIRTH_SPOUSE DATE;
alter table tither add MATIRAL_STATUS SMALLINT;
alter table tither alter column MATIRAL_STATUS SMALLINT;
alter table tither add REGISTER_DATE DATETIME;