// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Sispar.Infra.EF;

namespace Sispar.Infra.Migrations
{
    [DbContext(typeof(SisparDataContext))]
    [Migration("20200520174826_AdicionadaFKTither")]
    partial class AdicionadaFKTither
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Sispar.Domain.Entities.Tithe", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateContribution")
                        .HasColumnType("date");

                    b.Property<DateTime>("RegisterDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("TitherId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("ValueContribution")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("TitherId");

                    b.ToTable("Tithes");
                });

            modelBuilder.Entity("Sispar.Domain.Entities.Tither", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<short>("Active")
                        .HasColumnType("smallint");

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(200)")
                        .HasMaxLength(200);

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("date");

                    b.Property<string>("CPF")
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.Property<string>("Cellphone")
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.Property<DateTime?>("DateBirthSpouse")
                        .HasColumnType("date");

                    b.Property<DateTime?>("MarriegeDate")
                        .HasColumnType("date");

                    b.Property<short>("MatiralStatus")
                        .HasColumnType("smallint");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("NameSpouse")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<DateTime>("RegisterDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Telephone")
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.HasKey("Id");

                    b.ToTable("Tithers");

                    b.HasData(
                        new
                        {
                            Id = new Guid("b6d8217a-ead2-4d9c-abb6-185dfc231915"),
                            Active = (short)1,
                            Address = "rua sem saida",
                            BirthDate = new DateTime(2020, 5, 20, 17, 48, 25, 86, DateTimeKind.Utc).AddTicks(9905),
                            CPF = "999.999.999-99",
                            Cellphone = "11 9.9999-9999",
                            DateBirthSpouse = new DateTime(2020, 5, 20, 17, 48, 25, 87, DateTimeKind.Utc).AddTicks(4558),
                            MarriegeDate = new DateTime(2020, 5, 20, 17, 48, 25, 87, DateTimeKind.Utc).AddTicks(2711),
                            MatiralStatus = (short)0,
                            Name = "Jose",
                            NameSpouse = "Maria",
                            RegisterDate = new DateTime(2020, 5, 20, 17, 48, 25, 86, DateTimeKind.Utc).AddTicks(7618),
                            Telephone = "11 9.9999-9999"
                        });
                });

            modelBuilder.Entity("Sispar.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<short>("Active")
                        .HasColumnType("smallint");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<DateTime>("RegisterDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a20680e9-cea2-479e-ab2c-8604f314780f"),
                            Active = (short)1,
                            Password = "916c1678d3d28eb3e7798b9cf7acfbb6",
                            RegisterDate = new DateTime(2020, 5, 20, 17, 48, 25, 60, DateTimeKind.Utc).AddTicks(5078),
                            Username = "milton"
                        },
                        new
                        {
                            Id = new Guid("baac0a4d-2a00-48e3-a2e6-a2d0aa3e3ef0"),
                            Active = (short)1,
                            Password = "916c1678d3d28eb3e7798b9cf7acfbb6",
                            RegisterDate = new DateTime(2020, 5, 20, 17, 48, 25, 77, DateTimeKind.Utc).AddTicks(516),
                            Username = "felipe"
                        });
                });

            modelBuilder.Entity("Sispar.Domain.Entities.Tithe", b =>
                {
                    b.HasOne("Sispar.Domain.Entities.Tither", "Tither")
                        .WithMany("Tithes")
                        .HasForeignKey("TitherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
